//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerUpdate.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int idTovar { get; set; }
        public Nullable<decimal> PriceTovar { get; set; }
    
        public virtual Tovar Tovar { get; set; }
    }
}
