//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerUpdate.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int IdTovar { get; set; }
        public string NameTorar { get; set; }
        public int TypeTovar { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual TypeTovar TypeTovar1 { get; set; }
    }
}
